In [1]:
#Part 1
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

zeros_arr = np.zeros((3, 3))
print("Zeros Array:\n", zeros_arr)

ones_arr = np.ones((2, 4))
print("Ones Array:\n", ones_arr)

range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range Array: [0 2 4 6 8]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


In [3]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [4]:
#Part 2
import numpy as np

table = np.array([
    [5, 8, 2, 7],
    [1, 9, 4, 3],
    [6, 0, 11, 10],
    [12, 13, 14, 15]
])

print("Second row:", table[1, :])
print("Third column:", table[:, 2])
print("Sub-table R2-R3, C2-C3:\n", table[1:3, 1:3])

Second row: [1 9 4 3]
Third column: [ 2  4 11 14]
Sub-table R2-R3, C2-C3:
 [[ 9  4]
 [ 0 11]]


In [5]:
import numpy as np

scores = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 79],
    [55, 65, 72]
])

scores[:, 1] += 5
scores[0, :] = [100, 100, 100]
scores[:, 2] = 0

print("Updated scores:\n", scores)

Updated scores:
 [[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]


In [6]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([2, 4])

print("Element-wise multiplication:\n", A * B)
print("Matrix multiplication (A @ B):\n", A @ B)
print("Broadcasting (A * v):\n", A * v)

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication (A @ B):
 [[19 22]
 [43 50]]
Broadcasting (A * v):
 [[ 2  8]
 [ 6 16]]


In [7]:
import numpy as np

np.random.seed(42)
matrix = np.random.randint(-5, 6, (4, 4))
print("Random Matrix:\n", matrix)

vals, counts = np.unique(matrix, return_counts=True)
print("Unique values:", vals)
print("Counts:", counts)

# Part B: Unique Rows
a = np.array([
    [1, 0, 0],
    [1, 0, 0],
    [2, 3, 4]
])
unique_rows = np.unique(a, axis=0)
print("Unique rows:\n", unique_rows)

Random Matrix:
 [[ 1 -2  5  2]
 [-1  1  4 -3]
 [ 1  5  5  2]
 [-1 -2  2  2]]
Unique values: [-3 -2 -1  1  2  4  5]
Counts: [1 2 2 3 4 1 3]
Unique rows:
 [[1 0 0]
 [2 3 4]]


In [1]:
import numpy as np

x = np.array([2, 0, 1, 5, 4, 1, 9])
A = np.array([[3, 8, 1], [6, 2, 9]])

# argsort returns the indices that would sort an array
sorted_indices = np.argsort(x)
print("Indices of sorted x:", sorted_indices)

print("Sorted x:", np.sort(x))

print("Sorted A (axis 1):\n", np.sort(A, axis=1))

print("Sorted A (axis 0):\n", np.sort(A, axis=0))

Indices of sorted x: [1 2 5 0 4 3 6]
Sorted x: [0 1 1 2 4 5 9]
Sorted A (axis 1):
 [[1 3 8]
 [2 6 9]]
Sorted A (axis 0):
 [[3 2 1]
 [6 8 9]]
